name: Health Checks

on: push

env:
  ACTIONS_CI: "is_in_github"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install packages
        run: pip install pytest coverage Pillow
      - name: Run Python unit tests
        run: python3 -m pytest
      - name: Conduct coverage reporting
        run: coverage run --branch -m pytest main
      - name: Show coverage report
        run: coverage report -m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
